services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  node-app:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Adjust the path if needed
    container_name: node-app
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: postgres

volumes:
  pgdata:
